[package]
name = "todo_notes_cli"
version = "0.1.0"
edition = "2024"
license = "GPL-3.0"

[dependencies]
anyhow = "1.0.100"
chrono = "0.4.42"
serde = {version = "1.0.228", features = ["derive"]}
serde_json = "1.0.145"
uuid = {version = "1.19.0", features = ["v4", "serde"]}
